export default [
    {
      id: 'crushed-rock-roast',
      src: '/Assets/images/coffeepack1.png',
      images: [
        '/Assets/images/coffeepack1.png',
        '/Assets/images/coffeepack2.png',
        '/Assets/images/coffeepack3.png',
      ],
      coffeetype: 'BLEND',
      coffeetitle: 'Single Origin Espresso',
      coffeenotes: 'Cherry • Blackberry • Dark Chocolate',
      description: 'Bold and full-bodied, this dark roast blend brings together beans from Ethiopia and Brazil for a rich, smoky cup with deep notes of dark chocolate, ripe cherry and blackberry that linger long after the last sip.',
      badge: 'EXCLUSIVE',
      newDrop: true,
      price: 229,
      roast: 0.8,
      sizes: ['230g', '500g'],
    },
    {
      id: 'mild-decaf-roast',
      src: '/Assets/images/decafpack1.png',
      images: [
        '/Assets/images/decafpack1.png',
        '/Assets/images/decafpack2.png',
        '/Assets/images/decafpack3.png',
      ],
      coffeetype: 'SINGLE ORIGIN',
      coffeetitle: 'Mild decaf Roast',
      coffeenotes: 'Cacao • Vanilla • Soft Almond',
      description: 'A gentle, well-rounded decaf with soft body and a clean finish. All the ritual, none of the restlessness.',
      // badge: 'NEW',
      newDrop: false,
      price: 229,
      roast: 0.25,
      sizes: ['230g', '500g'],
    },
    {
      id: 'sunrise-single-origin',
      src: '/Assets/images/normalroast1.png',
      images: [
        '/Assets/images/normalroast1.png',
        '/Assets/images/normalroast2.png',
        '/Assets/images/normalroast3.png',
      ],
      coffeetype: 'SINGLE ORIGIN',
      coffeetitle: 'Sunrise Single Origin',
      coffeenotes: 'Citrus • Honey • Almond',
      description: 'A bright and delicate light roast grown in the highlands, this single origin coffee greets you with juicy citrus and honeyed sweetness, finishing with a soft, nutty almond note that makes every morning feel like sunrise.',
      // badge: 'NEW',
      newDrop: true,
      price: 249,
      roast: 0.25,
      sizes: ['230g', '500g'],
    },
];
